name: Check for New Episodes

on:
  schedule:
    # Run every day at midnight
    - cron: '0 0 * * *'
  # Also allow manual triggering
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-for-new-episodes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install script dependencies
        run: npm install googleapis dotenv
      
      - name: Create .env file
        run: |
          echo "YOUTUBE_API_KEY=${{ secrets.YOUTUBE_API_KEY }}" > ./scripts/.env
      
      - name: Run YouTube fetcher script
        run: node scripts/fetch-youtube.js
      
      - name: Check for changes
        id: git-check
        run: |
          git add -A
          if git diff --cached --exit-code; then
            echo "No new episodes found."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "New episodes found!"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add new Open Source Fridays episodes"
          title: "Add new Open Source Fridays episodes"
          body: |
            This PR automatically adds new episodes from the Open Source Fridays YouTube playlist.
            
            - Auto-generated by GitHub Actions
          branch: update-episodes
          base: main
